### ISSUE TITLE
[question/idea] use a headless browser for automatic prerender of pages

### ISSUE THREAD

**Issue by ctf0** [anthonygore/fake-ssr-vue-laravel#1]
am very new into this but i recently stumbled upon https://github.com/prerender/prerender which does the prerendering on-the-fly but currently it only works for crawlers however internally it uses http://phantomjs.org/ to cache the page,
so as https://laravel.com/docs/5.4/dusk which also does the same but for testing.

so i was thinking of having a server that run in the background and do the prerendering automatically on each page, 
maybe like configuring something for dusk and add a global middleware to check if we have a cache for the visited page and if not we run `php artisan dusk`

is this even possible <s>or are we better off using reversed-proxy or simpler use https://github.com/barryvdh/laravel-httpcache</s> ?

**Comment by anthonygore** [comment]
Hi, yeah that's basically what's happening in this project. The prerender plugin will be triggered by Webpack when you do a production build. I'm not sure where Dusk fits in to that though...

**Comment by ctf0** [comment]
maybe i wasnt clear enough.

i mean that we dont use `$initial_state` nor we need `render.sh`
all you will need to do is 

1. do your laravel coding as usual
2. install an npm package 
3. run a node server.

something like how prerender.io works
> install the middleware
$ git clone https://github.com/prerender/prerender.git
$ cd prerender
$ npm install
$ node server.js

thats was my initial intend, but because preprender.io is for crawlers only, i thought we could mimic the same with dusk which would work for all situations.
